// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: todos.sql

package db

import (
	"context"
)

const bulkDeleteTodosBySession = `-- name: BulkDeleteTodosBySession :exec
DELETE FROM todos
WHERE session_id = ?
`

func (q *Queries) BulkDeleteTodosBySession(ctx context.Context, sessionID string) error {
	_, err := q.exec(ctx, q.bulkDeleteTodosBySessionStmt, bulkDeleteTodosBySession, sessionID)
	return err
}

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (
    id,
    session_id,
    content,
    status,
    priority,
    position,
    created_at,
    updated_at,
    finished_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    strftime('%s', 'now'),
    strftime('%s', 'now'),
    CASE WHEN ?4 = 'completed' THEN strftime('%s', 'now') ELSE NULL END
) RETURNING id, session_id, content, status, priority, position, created_at, updated_at, finished_at
`

type CreateTodoParams struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	Content   string `json:"content"`
	Status    string `json:"status"`
	Priority  int64  `json:"priority"`
	Position  int64  `json:"position"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.queryRow(ctx, q.createTodoStmt, createTodo,
		arg.ID,
		arg.SessionID,
		arg.Content,
		arg.Status,
		arg.Priority,
		arg.Position,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Content,
		&i.Status,
		&i.Priority,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos
WHERE id = ?
`

func (q *Queries) DeleteTodo(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteTodoStmt, deleteTodo, id)
	return err
}

const getTodoByID = `-- name: GetTodoByID :one
SELECT id, session_id, content, status, priority, position, created_at, updated_at, finished_at
FROM todos
WHERE id = ? LIMIT 1
`

func (q *Queries) GetTodoByID(ctx context.Context, id string) (Todo, error) {
	row := q.queryRow(ctx, q.getTodoByIDStmt, getTodoByID, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Content,
		&i.Status,
		&i.Priority,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listTodosBySession = `-- name: ListTodosBySession :many
SELECT id, session_id, content, status, priority, position, created_at, updated_at, finished_at
FROM todos
WHERE session_id = ?
ORDER BY position ASC, created_at ASC
`

func (q *Queries) ListTodosBySession(ctx context.Context, sessionID string) ([]Todo, error) {
	rows, err := q.query(ctx, q.listTodosBySessionStmt, listTodosBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Content,
			&i.Status,
			&i.Priority,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodoStatus = `-- name: UpdateTodoStatus :one
UPDATE todos
SET
    status = ?1,
    finished_at = CASE WHEN ?1 = 'completed' THEN strftime('%s', 'now') ELSE NULL END
WHERE id = ?2
RETURNING id, session_id, content, status, priority, position, created_at, updated_at, finished_at
`

type UpdateTodoStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateTodoStatus(ctx context.Context, arg UpdateTodoStatusParams) (Todo, error) {
	row := q.queryRow(ctx, q.updateTodoStatusStmt, updateTodoStatus, arg.Status, arg.ID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Content,
		&i.Status,
		&i.Priority,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}
